
language: ruby

git:
  depth: 1

branches:
  only:
  - master

cache:
  timeout: 10000
  bundler: true
  directories:
    - $HOME/btsync/
    - $HOME/mirrors/

install:
  - wget https://download-cdn.resilio.com/stable/linux-x64/resilio-sync_x64.tar.gz -O /tmp/btsync.tar.gz
  - cd /tmp/ && tar -xvf /tmp/btsync.tar.gz && cd -
  - sudo cp /tmp/rslsync /usr/local/bin/
  - bundle install

before_script:
  - bundle exec rake init --quiet
  - rslsync --config btsync.conf.json

script:
  - bundle exec rake timing-output --quiet &
  - bundle exec rake sync[5] --quiet
  - bundle exec rake deploy --quiet
