name: Sync

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */12 * * *

jobs:
  backup:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.3
          bundler-cache: true
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Git Config
        run: |
          git config --global user.name program-think-mirrors
          git config --global user.email program-think-mirrors@github.com
          git config --global push.default simple

      - name: Pull
        uses: actions/checkout@v2
        with:
          repository: program-think-mirrors/gfw
          path: gfw
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 1
      - uses: actions/checkout@v2
        with:
          repository: program-think-mirrors/blog
          path: blog
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 1
      - uses: actions/checkout@v2
        with:
          repository: program-think-mirrors/books
          path: books
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 1

      - name: Install BT Sync
        run: |
          wget -nv https://download-cdn.resilio.com/stable/linux-x64/resilio-sync_x64.tar.gz -O /tmp/btsync.tar.gz
          cd /tmp/ && tar -xvf /tmp/btsync.tar.gz && cd -
          sudo cp /tmp/rslsync /usr/local/bin/
      - name: Install Dependencies
        run: bundle install

      - name: Set up BT Sync
        run: |
          bundle exec rake init --quiet
          rslsync --config btsync.conf.json

      - name: Sync
        run: |
          bundle exec rake sync[10] --quiet
          pkill -f "rslsync"
      - name: Push to Github
        run: bundle exec rake deploy --quiet

      - name: Update Date
        run: |
          git pull
          date -u > updated
          git add updated
          git commit -m "$(date -uI)"
          git push
