name: Sync

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron:  0 */12 * * *

jobs:
  sync:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
          - { repo: program-think-mirrors/gfw, path: gfw }
          - { repo: program-think-mirrors/blog, path: blog }
          - { repo: program-think-mirrors/books, path: books }
          - { repo: program-think-mirrors/books, path: history, ref: history }
          - { repo: program-think-mirrors/books, path: politics, ref: politics }
      fail-fast: false

    env:
      REPO_REF: ${{ matrix.ref || 'master' }}
      REPO_PATH: ${{ matrix.path }}
      WAIT_TIME: ${{ matrix.time || 30 }} # min

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.3
          bundler-cache: true
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Git Config
        run: |
          git config --global user.name program-think-mirrors
          git config --global user.email program-think-mirrors@github.com
          git config --global push.default simple
          git config --global pull.ff only 

      - name: Pull
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REPO_REF }}
          repository: ${{ matrix.repo }}
          path: ${{ matrix.path }}
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: 1

      - name: Install BT Sync
        run: |
          wget -nv https://download-cdn.resilio.com/stable/linux-x64/resilio-sync_x64.tar.gz -O /tmp/btsync.tar.gz
          cd /tmp/ && tar -xvf /tmp/btsync.tar.gz && cd -
          sudo cp /tmp/rslsync /usr/local/bin/
      - name: Install Dependencies
        run: bundle install

      - name: Set up BT Sync
        run: |
          bundle exec rake init --quiet
          rslsync --config btsync.$REPO_PATH.conf.json

      - name: Sync
        run: |
          bundle exec rake sync[$WAIT_TIME] --quiet
          pkill -f "rslsync"
      - name: Push to Github
        run: bundle exec rake deploy --quiet

  update-meta:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Git Config
        run: |
          git config --global user.name program-think-mirrors
          git config --global user.email program-think-mirrors@github.com
      - name: Update Metadata
        run: |
          git pull
          date -u > updated
          git add updated
          git commit -m "$(date -uI)"
          git push

  write-refs:
    runs-on: ubuntu-latest
    needs: sync
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/update-ref.js`)
            await script({ github })
